controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy = -130
        scene.cameraShake(3, 500)
        music.jumpUp.play()
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    scene.setBackgroundImage(assets.image`我的影像28`)
})
let mySprite: Sprite = null
scene.setBackgroundColor(1)
mySprite = sprites.create(assets.image`我的影像2`, SpriteKind.Player)
let mySprite2 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mySprite3 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mySprite4 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mySprite5 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mySprite10 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mySprite6 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mySprite7 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mySprite9 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mySprite8 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mysprite11 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let myspite12 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mysprite13 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mysprite14 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mysprite15 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mysprite17 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mySprite16 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mysprite18 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mysprite19 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mysprite20 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mysprite21 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mysprite22 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mysprite23 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
let mysprite24 = sprites.create(assets.image`我的影像12`, SpriteKind.Projectile)
let mysprite25 = sprites.create(assets.image`我的影像10`, SpriteKind.Projectile)
scene.cameraFollowSprite(mySprite)
mysprite11.setPosition(100, 121)
mySprite.setPosition(8, 100)
mySprite2.setPosition(1000, 121)
mySprite3.setPosition(800, 121)
mySprite4.setPosition(1100, 121)
mySprite5.setPosition(1525, 121)
mySprite6.setPosition(2000, 121)
mySprite7.setPosition(900, 121)
mySprite8.setPosition(500, 121)
mySprite9.setPosition(400, 121)
mySprite10.setPosition(300, 121)
mysprite11.setPosition(100, 121)
myspite12.setPosition(200, 121)
mysprite13.setPosition(600, 121)
mysprite14.setPosition(700, 121)
mysprite15.setPosition(1200, 121)
mySprite16.setPosition(1300, 121)
mysprite17.setPosition(1400, 121)
mysprite18.setPosition(1632, 121)
mysprite19.setPosition(1740, 121)
mysprite20.setPosition(1851, 121)
mysprite21.setPosition(1960, 121)
mysprite22.setPosition(2074, 121)
mysprite23.setPosition(2228, 121)
mysprite24.setPosition(2348, 121)
mysprite25.setPosition(2479, 121)
mySprite.ax = 2
mySprite.ay = 200
mySprite.setVelocity(25, 0)
tiles.setCurrentTilemap(tilemap`層級2`)
info.setLife(1)
game.onUpdate(function () {
    if (mySprite.isHittingTile(CollisionDirection.Right)) {
        scene.setBackgroundImage(assets.image`我的影像27`)
        game.over(true, effects.confetti)
    }
})
